version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086" # UI + API
    environment:
      # one-time initial setup
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "changeme"
      INFLUXDB_HTTP_LOG_ENABLED: "true"
      DOCKER_INFLUXDB_INIT_ORG:       "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET:    "jmeter"
      DOCKER_INFLUXDB_INIT_RETENTION: "30d"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "super-secret-token"
    volumes:
      - influxdb-data:/var/lib/influxdb2     # time-series data
      - influxdb-config:/etc/influxdb2       # config, tokens
      - ./influxdb/init:/docker-entrypoint-initdb.d  # initialization scripts
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # JMeter can now connect directly to influxdb on localhost:8086
    # since you've configured /etc/hosts to point influxdb to 127.0.0.1
    # and we're using host network mode

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    ports:
      - "4000:3000" # Grafana UI
    environment:
      GF_SECURITY_ADMIN_USER:     "${GF_ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_ADMIN_PASSWORD:-admin}"
      GF_USERS_ALLOW_SIGN_UP:      "false"
    volumes:
      - grafana-data:/var/lib/grafana                 # dashboards, plugins
      - ./grafana/provisioning:/etc/grafana/provisioning  # auto-datasource
      - ./grafana/dashboards:/var/lib/grafana/dashboards  # dashboard files

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
