version: "3.9"

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086" # UI + API
    environment:
      # one-time initial setup
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "${INFLUXDB_USER:-admin}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUXDB_PASSWORD:-changeme}"
      DOCKER_INFLUXDB_INIT_ORG:       "${INFLUXDB_ORG:-my-org}"
      DOCKER_INFLUXDB_INIT_BUCKET:    "${INFLUXDB_BUCKET:-metrics}"
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUXDB_TOKEN:-super-secret-token}"
    volumes:
      - influxdb-data:/var/lib/influxdb2     # time-series data
      - influxdb-config:/etc/influxdb2       # config, tokens

  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    ports:
      - "4000:3000" # Grafana UI
    environment:
      GF_SECURITY_ADMIN_USER:     "${GF_ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_ADMIN_PASSWORD:-admin}"
      GF_USERS_ALLOW_SIGN_UP:      "false"
    volumes:
      - grafana-data:/var/lib/grafana                 # dashboards, plugins
      - ./grafana/provisioning:/etc/grafana/provisioning  # auto-datasource

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
